### ISSUE TITLE
Presentation issues in mobile Safari

### ISSUE THREAD

**Issue by nathanielmott** [RealOrangeOne/website#1] opened 2022-10-30 12:18 UTC
Both these problems are on iOS 16.1 in Safari with 1Blocker enabled running on iPhone 14 Pro. (I haven’t tested any other configurations.)

First: The sticky header in articles results in jittery scrolling. This is a common problem with headers that aren’t static, and instead “catch up” to the article as it’s scrolling.

Second: The “Posts” feed is… busted. (I have attempted to attach a screenshot to this issue, but have not done so before, so we’ll see!)

![2615B574-3DAB-4232-9653-AF7A91BFEC10](https://user-images.githubusercontent.com/46465718/198877985-4ecd6368-c5be-4ad8-9a6b-4f1879d3caf9.png)

**Comment by RealOrangeOne** [comment] 2022-10-30 13:03
> The sticky header in articles results in jittery scrolling

I think the cause of this is that the hero actually changes size based on whether it's stuck to the top or not. Page subtitles and breadcrumbs get hidden to thin it down a bit. That does cause some jitter, I'll see if I can tone that down a bit.

> The “Posts” feed is… busted

Wow, that does look like garbage. Apparently the responsive testing I was doing wasn't quite good enough. Will see if I can fix it.

**Comment by RealOrangeOne** [comment] 2022-10-30 14:03
I've just deployed https://github.com/RealOrangeOne/website/commit/053f44bf35f4d7960c00ac9da041a29856df27e8 and https://github.com/RealOrangeOne/website/commit/93c06b3fe7f05b696b4b10e88cb08e0e5b9d1804, and I think that's fixed both. I don't have an iPhone to test with, but I _think_ this should have resolved both issues.

**Comment by nathanielmott** [comment] 2022-10-30 17:21
The issue with the Posts page has been fixed. Scrolling behavior seems to be improved, but is still weird at the end of a scroll or when changing direction. Working in getting a screen recording to show what I mean.

**Comment by RealOrangeOne** [comment] 2023-06-02 15:12
Closing, as a lot has changed on the site in 9 months. If it's still an issue, please post a video.

**Closed as completed by RealOrangeOne** 2023-06-02 15:12 UTC
